# run_agent.ps1

# Catch the variables passed from n8n
param (
    [Parameter(Mandatory=$true)]
    [string]$TicketID,
    
    [Parameter(Mandatory=$true)]
    [string]$Instruction
)

# 0. The Bulletproof Routing (Force the script into the right folder)
Set-Location -Path "D:\jira-automation"
Write-Output "✅ Reached the folder safely. Ticket: $TicketID"

# 1. Ensure we are on a clean main branch and create the feature branch
git checkout main
git pull origin main
git checkout -b "feature/$TicketID"
Write-Output "✅ Git branch created."

# 2. Run Aider headless to apply changes
# It will automatically pick up the GEMINI_API_KEY from your system variables
aider --model gemini/gemini-2.5-flash --message "$Instruction" --yes-always

# 3. Commit and push the new code
git add .
git commit -m "AI Agent: Resolving $TicketID"
git push -u origin "feature/$TicketID"
Write-Output "✅ Pushed to GitHub."

# 4. Create the Pull Request using GitHub CLI
# We capture the output (the URL) into a variable
$PR_URL = gh pr create --title "Resolve $TicketID" --body "Automated PR generated by AI pipeline." --head "feature/$TicketID"
Write-Output "✅ PR Created: $PR_URL"

# 5. Output ONLY the URL so n8n can read it and put it in the Google Sheet
Write-Output $PR_URL